#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo "Usage: $0 <SENTRY_DSN> <TRANSLATIONS_API_KEY>"
fi

cat > .env << EOL
DEV_API_ENDPOINT=
DEV_SOCKETCLUSTER_HOST=
DEV_SOCKETCLUSTER_PORT=
DEV_TILE_SERVER=
DEV_TILE_TEMPLATE=
DEV_TRANSLATIONS_API_ENDPOINT=
SENTRY_DSN=$1
TRANSLATIONS_API_KEY=$2
EOL
