const theme = {
  $color_primary: '#070D39',
  $color_secondary: '#11195B',
  $color_tertiary: '#4990DD',
  $color_grey: '#747D7D',
  $color_grey_dark: '#4A4A4A',
  $color_grey_light: '#D8D8D8',
  $color_grey_lighter: '#F8F8F8',
  $color_success: '#407505',
  $color_error: '#D0011C',
  $color_medium_error: 'darkorange',
  $color_highlight: '#FFFFD5',
  $color_near_black: '#010101',
  $color_black: '#000000',
  $color_white: '#FFFFFF',
  $font_size_small: '0.625rem',
  $font_size_smaller: '0.75rem',
  $font_size_normal: '0.875rem',
  $font_size_big: '1.25rem',
  $font_text: '"Open Sans", "Segoe UI", Tahoma, sans-serif',
  $font_title: '"Open Sans", "Segoe UI", Tahoma, sans-serif',
  $line_height: '1.5rem',
  $border_radius: '.25rem',
  $border_radius_small: '.125rem',
  $border_radius_bigger: '.375rem',
  $border_radius_big: '.5rem',
  $gap: '1rem',
  $gap_big: '2rem',
  $gap_medium: '1.5rem',
  $gap_smaller: '0.625rem',
  $gap_small: '.5rem',
  $gap_tinier: '.25rem',
  $gap_tiny: '.125rem',
  $shadow_offset: { width: 0, height: 2 },
  $shadow_radius: 2,
  $elevation: 2,
  $shadow_color: '#000000',
  $shadow_opacity: 0.25,
  /* Turn on for outline debugging */
  //$outline: 1,
};

export default theme;
